nav:
  - 最新博客: index.md
  - 每日速览: articles/express
  - 量化课程:
    - 因子投资与机器学习策略:
      - 简介: articles/coursea/factor-ml/intro.md
      - 课程大纲: articles/coursea/factor-ml/syllabus.html
      - 课程预览: http://ke.quantide.cn/academy/login?preview=true&course=fa
    - 量化二十四课:
      - 简介: articles/coursea/24lectures/intro.md
      - 课程大纲: articles/coursea/24lectures/syllabus.html
      - FAQ: articles/coursea/24lectures/faq.md
      - 内容详情: articles/coursea/24lectures/detail.md
      - 课程预览: http://ke.quantide.cn/academy/login?preview=true&course=l24
    - 量化中的Numpy和Pandas:
      - 简介: articles/coursea/numpy-pandas/intro.md
      - 课程大纲: articles/coursea/numpy-pandas/syllabus.html
  - 量化产品: articles/products
  - 策略研究: articles/investment
  - 免费教程: articles/python
  - 播客（双日更）: https://www.youtube.com/channel/UCu7m4hFZ3any38pyVCBa06w
  - 文章分类: tags
  - Follow Us:
    - contact.md
